# Generated by Django 2.1 on 2018-08-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('school', models.CharField(help_text='School currently attending', max_length=200, verbose_name='School')),
                ('shs_track', models.CharField(help_text='Current SHS Track', max_length=100, verbose_name='SHS Track')),
                ('projected_course', models.CharField(help_text='First choice of Course', max_length=200, verbose_name='Course')),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('qr_code', models.CharField(max_length=200, null=True)),
                ('date_registered', models.DateTimeField(editable=False)),
                ('date_modified', models.DateTimeField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
