# Generated by Django 2.1 on 2018-08-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='qr_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
