# Generated by Django 2.1 on 2018-08-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20180807_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='shs_strand',
            field=models.CharField(blank=True, help_text='Strand of you SHS Track (blank if not applicable', max_length=100, null=True, verbose_name='SHS Strand'),
        ),
    ]
