# Generated by Django 2.1 on 2018-08-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_event_event_registration_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_registration_url',
            field=models.URLField(blank=True, null=True, verbose_name='Event Registration Link'),
        ),
    ]
