# Generated by Django 2.1 on 2018-08-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_event_event_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.ImageField(upload_to='logos/', verbose_name='Logo for the event'),
        ),
    ]
