# Generated by Django 2.1 on 2018-08-08 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20180808_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='shs_strand',
        ),
    ]
