# Generated by Django 2.1 on 2018-08-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20180808_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='qr_code',
            field=models.ImageField(height_field=128, null=True, upload_to='qrcode', width_field=128),
        ),
    ]
