# Generated by Django 2.1 on 2018-08-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20180809_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='qr_code',
            field=models.ImageField(null=True, upload_to='qrcode'),
        ),
    ]
