# Generated by Django 2.1 on 2018-08-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20180809_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='qr_added',
            field=models.BooleanField(default=False),
        ),
    ]
