# Generated by Django 2.1 on 2018-08-10 11:39

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_auto_20180810_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=s3direct.fields.S3DirectField(),
        ),
    ]
