# Generated by Django 2.1 on 2018-08-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_auto_20180811_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_uuid',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
