# Generated by Django 2.1 on 2018-08-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_event_event_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Number'),
        ),
    ]
