# Generated by Django 2.1 on 2019-08-07 15:27

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_student_mobile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoollist',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=s3direct.fields.S3DirectField(blank=True, max_length=250, null=True),
        ),
    ]
