# Generated by Django 2.1 on 2019-08-08 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_auto_20190807_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registered_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Event'),
        ),
    ]
