# Generated by Django 2.1 on 2019-08-15 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_auto_20190814_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolOfficial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('course_taken', models.CharField(blank=True, help_text='Course taken', max_length=200, null=True, verbose_name='Course')),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Number')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('qr_code', models.ImageField(null=True, upload_to='qrcode')),
                ('date_registered', models.DateTimeField(editable=False)),
                ('date_modified', models.DateTimeField()),
                ('qr_added', models.BooleanField(default=False)),
                ('registered_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Event')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.SchoolList')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
