# Generated by Django 2.1 on 2019-08-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_schoolofficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolofficial',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Designation/Position'),
        ),
    ]
